#pragma once

#define DCHECKERS_DEVICE 0x8000

#define IOCTL_DCHECKERS_SET_PROTECT_PID CTL_CODE(DCHECKERS_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_DCHECKERS_STOP_PROTECTING CTL_CODE(DCHECKERS_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_DCHECKERS_BLOCK_PROCESS_CREATION CTL_CODE(DCHECKERS_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_DCHECKERS_STOP_BLOCKING_PROCESS_CREATION CTL_CODE(DCHECKERS_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)

#define IOCTL_DCHECKERS_KILL_SYSTEM CTL_CODE(DCHECKERS_DEVICE, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS)